#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar -allRegions
runParallel $(getApplication) --use-hwthread-cpus
runApplication reconstructPar -allRegions

